/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.110
 * Generated at: 2025-12-07 20:29:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.persistence.*;
import org.openxava.jpa.XPersistence;
import org.example.ProyectoPOO.model.bodega.Paquete;
import org.example.ProyectoPOO.model.bodega.Movimiento;
import java.util.List;
import java.time.format.DateTimeFormatter;

public final class rastreo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.persistence");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("org.openxava.jpa.XPersistence");
    _jspx_imports_classes.add("org.example.ProyectoPOO.model.bodega.Movimiento");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.example.ProyectoPOO.model.bodega.Paquete");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Portal de Servicios - ProyectoPOO</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"rastreo.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <h1>Portal de Servicios</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- PESTAÑAS -->\r\n");
      out.write("    <div class=\"tabs\">\r\n");
      out.write("        <button class=\"tab-link active\" data-target=\"Rastreo\">Rastreo de Paquetes</button>\r\n");
      out.write("        <button class=\"tab-link\" data-target=\"Cotizar\">Cotizar Envío</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- TAB RASTREO -->\r\n");
      out.write("    <div id=\"Rastreo\" class=\"tab-content active\">\r\n");
      out.write("        <div class=\"search-box\">\r\n");
      out.write("            <form method=\"get\" action=\"rastreo.jsp\" class=\"search-form\">\r\n");
      out.write("                <label for=\"tracking\">Ingresa tu código de rastreo</label>\r\n");
      out.write("                <input type=\"text\"\r\n");
      out.write("                       id=\"tracking\"\r\n");
      out.write("                       name=\"tracking\"\r\n");
      out.write("                       placeholder=\"Ej: USA0001, USA0002...\"\r\n");
      out.write("                       required\r\n");
      out.write("                       value=\"");
      out.print( request.getParameter("tracking") != null ? request.getParameter("tracking") : "" );
      out.write("\">\r\n");
      out.write("                <button type=\"submit\">\r\n");
      out.write("                    <span>🔍</span>\r\n");
      out.write("                    <span>Rastrear</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");

            String trackingCode = request.getParameter("tracking");

            if (trackingCode != null && !trackingCode.trim().isEmpty()) {
                EntityManager em = XPersistence.getManager();

                try {
                    String jpql = "SELECT p FROM Paquete p WHERE p.trackingProveedor = :code";
                    TypedQuery<Paquete> query = em.createQuery(jpql, Paquete.class);
                    query.setParameter("code", trackingCode.trim());

                    Paquete paquete = query.getSingleResult();

                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"result-card\">\r\n");
      out.write("            <div class=\"result-header\">\r\n");
      out.write("                <h3>Paquete #");
      out.print( paquete.getId() );
      out.write("</h3>\r\n");
      out.write("                <span class=\"status-badge\">");
      out.print( paquete.getEstadoActual() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <p><strong>Descripción:</strong> ");
      out.print( paquete.getDescripcion() );
      out.write("</p>\r\n");
      out.write("            <p><strong>Código de tracking:</strong> ");
      out.print( paquete.getTrackingProveedor() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("\r\n");
      out.write("            <h4>Ubicación actual</h4>\r\n");
      out.write("            <p>\r\n");
      out.write("                ");
      out.print( (paquete.getUbicacionActual() != null)
                        ? paquete.getUbicacionActual().getNombre()
                        : "En tránsito internacional / Sin sucursal asignada" );
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            ");

                List<Movimiento> historial = paquete.getHistorial();
                if (historial != null && !historial.isEmpty()) {
            
      out.write("\r\n");
      out.write("            <h4>Historial de movimientos</h4>\r\n");
      out.write("            <div class=\"timeline\">\r\n");
      out.write("                ");

                    for (Movimiento mov : historial) {
                
      out.write("\r\n");
      out.write("                <div class=\"timeline-item\">\r\n");
      out.write("                    <strong>");
      out.print( mov.getEstado() );
      out.write("</strong><br>\r\n");
      out.write("                    <small>\r\n");
      out.write("                        ");
      out.print( (mov.getTimestamp() != null)
                                ? mov.getTimestamp().format(formatter)
                                : "" );
      out.write("\r\n");
      out.write("                    </small>\r\n");
      out.write("                    <p>");
      out.print( mov.getDescripcion() != null ? mov.getDescripcion() : "" );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            } else {
            
      out.write("\r\n");
      out.write("            <p class=\"info-text\">No hay movimientos registrados aún.</p>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");

        } catch (NoResultException e) {
        
      out.write("\r\n");
      out.write("        <div class=\"result-card\">\r\n");
      out.write("            <h3 class=\"error-msg\">No encontrado</h3>\r\n");
      out.write("            <p>No pudimos encontrar un paquete con el código <strong>");
      out.print( trackingCode );
      out.write("</strong>.</p>\r\n");
      out.write("            <p class=\"info-text\">Verifica que el código esté correcto y que el envío esté registrado en el sistema.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

        } catch (Exception e) {
        
      out.write("\r\n");
      out.write("        <p class=\"error-msg\">\r\n");
      out.write("            Error del sistema: ");
      out.print( e.getMessage() );
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("        ");

                e.printStackTrace();
            }
        } else if (request.getParameter("tracking") != null) {
        
      out.write("\r\n");
      out.write("        <p class=\"info-text\">\r\n");
      out.write("            Ingresa un código de rastreo en el panel superior para ver el estado de tu envío.\r\n");
      out.write("        </p>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- TAB COTIZAR -->\r\n");
      out.write("    <div id=\"Cotizar\" class=\"tab-content\">\r\n");
      out.write("        <div class=\"search-box\">\r\n");
      out.write("            <form id=\"cotizar-form\" class=\"search-form\">\r\n");
      out.write("                <label for=\"peso\">Peso del producto (libras)</label>\r\n");
      out.write("                <input type=\"number\" id=\"peso\" name=\"peso\" placeholder=\"Ej: 10\" required step=\"0.01\" min=\"0.01\">\r\n");
      out.write("\r\n");
      out.write("                <label for=\"metodo-envio\">Método de Envío</label>\r\n");
      out.write("                <select id=\"metodo-envio\" name=\"metodo-envio\">\r\n");
      out.write("                    <option value=\"aereo\">Aéreo ($7.50/libra)</option>\r\n");
      out.write("                    <option value=\"maritimo\">Marítimo ($2.50/libra)</option>\r\n");
      out.write("                </select>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\">\r\n");
      out.write("                    <span>💲</span>\r\n");
      out.write("                    <span>Calcular</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"resultado-cotizacion\" class=\"result-card\" style=\"display: none;\">\r\n");
      out.write("            <h3>Resultado de la Cotización</h3>\r\n");
      out.write("            <p id=\"costo-envio\"></p>\r\n");
      out.write("            <p id=\"detalle-envio\"></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        © ");
      out.print( java.time.Year.now() );
      out.write(" ProyectoPOO\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("        // Manejo de pestañas (delegación simple)\r\n");
      out.write("        document.querySelectorAll('.tab-link').forEach(function(btn) {\r\n");
      out.write("            btn.addEventListener('click', function (evt) {\r\n");
      out.write("                var target = btn.getAttribute('data-target');\r\n");
      out.write("                if (!target) return;\r\n");
      out.write("\r\n");
      out.write("                // ocultar todos los contenidos y quitar active de botones\r\n");
      out.write("                document.querySelectorAll('.tab-content').forEach(function(tc){ tc.classList.remove('active'); });\r\n");
      out.write("                document.querySelectorAll('.tab-link').forEach(function(b){ b.classList.remove('active'); });\r\n");
      out.write("\r\n");
      out.write("                var content = document.getElementById(target);\r\n");
      out.write("                if (content) content.classList.add('active');\r\n");
      out.write("                btn.classList.add('active');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Listener seguro para el formulario de cotización\r\n");
      out.write("        var cotizarForm = document.getElementById('cotizar-form');\r\n");
      out.write("        if (cotizarForm) {\r\n");
      out.write("            cotizarForm.addEventListener('submit', function (e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("                var pesoInput = document.getElementById('peso');\r\n");
      out.write("                var metodoSelect = document.getElementById('metodo-envio');\r\n");
      out.write("                var resultadoCard = document.getElementById('resultado-cotizacion');\r\n");
      out.write("                var costoElem = document.getElementById('costo-envio');\r\n");
      out.write("                var detalleElem = document.getElementById('detalle-envio');\r\n");
      out.write("\r\n");
      out.write("                var peso = parseFloat(pesoInput.value);\r\n");
      out.write("                var metodo = metodoSelect.value;\r\n");
      out.write("                var costo = 0;\r\n");
      out.write("                var detalle = '';\r\n");
      out.write("\r\n");
      out.write("                if (isNaN(peso) || peso <= 0) {\r\n");
      out.write("                    alert(\"Por favor, ingrese un peso válido mayor que 0.\");\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (metodo === 'aereo') {\r\n");
      out.write("                    costo = peso * 7.50;\r\n");
      out.write("                    detalle = \"Envío aéreo: tiempo estimado de 24 a 72 horas. Ideal cuando quieres tu paquete lo más rápido posible.\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    costo = peso * 2.50;\r\n");
      out.write("                    detalle = \"Envío marítimo: tiempo estimado de 12 a 15 días. Ideal para productos pesados o envíos en volumen.\";\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // Mostrar resultados\r\n");
      out.write("                costoElem.innerText = 'El costo estimado del envío es: $' + costo.toFixed(2);\r\n");
      out.write("                detalleElem.innerText = detalle;\r\n");
      out.write("                if (resultadoCard) resultadoCard.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("                // Opcional: cambiar a la pestaña Cotizar si no está activa\r\n");
      out.write("                var cotizarTabBtn = document.querySelector('.tab-link[data-target=\"Cotizar\"]');\r\n");
      out.write("                if (cotizarTabBtn && !document.getElementById('Cotizar').classList.contains('active')) {\r\n");
      out.write("                    cotizarTabBtn.click();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
